"""empty message

Revision ID: 13be8a807a57
Revises: 65d0fba6252f
Create Date: 2021-02-02 03:55:18.033826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13be8a807a57'
down_revision = '65d0fba6252f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
